# Mumbai House Price Prediction:

# Importing Libraries and Loading the Data:

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [36]:
df = pd.read_csv("data/mumbai_housing_price_dataset_v2.csv")

df.head()

,locality,zone,bhk,property_type,carpet_area_sqft,floor_number,total_floors,age_of_building_years,furnishing_status,distance_to_station_km,...,is_gated_society,amenities_count,parking_available,sea_facing_view,possession_status,rera_registered,flood_prone_zone,water_supply_hours_per_day,society_maintenance_per_sqft,price_lakhs
0,Dahisar,Western Suburbs,1,Apartment,372,5,5,44.0,Semi-furnished,4.16,...,Yes,8,Yes,No,Ready to Move,Yes,Yes,16.6,11.98,51.36
1,Thane West,Thane,2,Apartment,744,4,5,2.0,Fully-furnished,5.09,...,No,1,No,No,Ready to Move,Yes,No,11.3,3.14,80.60
2,Vikhroli,Central Suburbs,2,Apartment,569,16,22,0.0,Semi-furnished,1.98,...,No,3,Yes,No,Ready to Move,Yes,No,16.2,3.78,108.25
3,Goregaon,Western Suburbs,2,Apartment,576,5,9,1.0,Fully-furnished,3.14,...,Yes,3,Yes,No,Ready to Move,Yes,No,19.0,7.44,127.50
4,Juhu,Western Suburbs,1,Apartment,382,0,22,2.0,Semi-furnished,2.92,...,No,0,No,No,Under Construction,Yes,No,19.5,3.02,156.58

# Understanding the Data:

In [37]:
print("Dataset shape:", df.shape)

Dataset shape: (5000, 21)

In [38]:
print("Information about the Data:")
df.info()

Information about the Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   locality                      5000 non-null   object
 1   zone                          5000 non-null   object
 2   bhk                           5000 non-null   int64
 3   property_type                 5000 non-null   object
 4   carpet_area_sqft              5000 non-null   int64
 5   floor_number                  5000 non-null   int64
 6   total_floors                  5000 non-null   int64
 7   age_of_building_years         4894 non-null   float64
 8   furnishing_status             5000 non-null   object
 9   distance_to_station_km        4931 non-null   float64
 10  distance_to_business_hub_km   5000 non-null   float64
 11  is_gated_society              5000 non-null   object
 12  amenities_count               5000 non-null   int64
 13  parking_available             5000 non-null   object
 14  sea_facing_view               5000 non-null   object
 15  possession_status             5000 non-null   object
 16  rera_registered               5000 non-null   object
 17  flood_prone_zone              5000 non-null   object
 18  water_supply_hours_per_day    4904 non-null   float64
 19  society_maintenance_per_sqft  4909 non-null   float64
 20  price_lakhs                   5000 non-null   float64
dtypes: float64(6), int64(5), object(10)
memory usage: 820.4+ KB

In [39]:
print("\nMissing values:")
print(df.isnull().sum())

Missing values:
locality                          0
zone                              0
bhk                               0
property_type                     0
carpet_area_sqft                  0
floor_number                      0
total_floors                      0
age_of_building_years           106
furnishing_status                 0
distance_to_station_km           69
distance_to_business_hub_km       0
is_gated_society                  0
amenities_count                   0
parking_available                 0
sea_facing_view                   0
possession_status                 0
rera_registered                   0
flood_prone_zone                  0
water_supply_hours_per_day       96
society_maintenance_per_sqft     91
price_lakhs                       0
dtype: int64

In [40]:
print("Description of our Data:")
df.describe()

Description of our Data:

,bhk,carpet_area_sqft,floor_number,total_floors,age_of_building_years,distance_to_station_km,distance_to_business_hub_km,amenities_count,water_supply_hours_per_day,society_maintenance_per_sqft,price_lakhs
count,5000.000000,5000.000000,5000.000000,5000.000000,4894.000000,4931.000000,5000.000000,5000.000000,4904.000000,4909.000000,5000.000000
mean,2.048400,829.271400,9.605600,19.449400,8.072946,2.349919,20.016660,4.033800,16.223430,6.549784,216.523752
std,0.895443,403.386918,7.883126,9.249138,7.915440,1.376444,10.099604,2.572777,3.111375,2.478555,193.936441
min,1.000000,320.000000,0.000000,4.000000,0.000000,0.200000,0.900000,0.000000,5.800000,2.030000,21.270000
25%,1.000000,559.750000,3.000000,11.000000,2.000000,1.250000,12.100000,2.000000,14.100000,4.650000,96.777500
50%,2.000000,734.000000,8.000000,19.000000,6.000000,2.110000,19.500000,4.000000,16.200000,6.150000,153.765000
75%,3.000000,941.000000,14.000000,27.000000,11.000000,3.265000,27.400000,6.000000,18.300000,8.200000,265.137500
max,4.000000,2398.000000,35.000000,35.000000,45.000000,7.990000,46.000000,8.000000,24.000000,13.320000,1999.380000

# Handle Missing Values:

In [41]:
cols_with_nulls = [
    "age_of_building_years",
    "distance_to_station_km",
    "water_supply_hours_per_day",
    "society_maintenance_per_sqft"
]

for col in cols_with_nulls:
    df[col] = df[col].fillna(df[col].mean())

print(df[cols_with_nulls].isnull().sum())

age_of_building_years           0
distance_to_station_km          0
water_supply_hours_per_day      0
society_maintenance_per_sqft    0
dtype: int64

# One Hot Encoding:

In [42]:
categorical_cols = [
    "locality",
    "zone",
    "property_type",
    "furnishing_status",
    "is_gated_society",
    "parking_available",
    "sea_facing_view",
    "possession_status",
    "rera_registered",
    "flood_prone_zone"
]

df_encoded = pd.get_dummies(
    df,
    columns=categorical_cols
)

df_encoded.head()

,bhk,carpet_area_sqft,floor_number,total_floors,age_of_building_years,distance_to_station_km,distance_to_business_hub_km,amenities_count,water_supply_hours_per_day,society_maintenance_per_sqft,...,parking_available_No,parking_available_Yes,sea_facing_view_No,sea_facing_view_Yes,possession_status_Ready to Move,possession_status_Under Construction,rera_registered_No,rera_registered_Yes,flood_prone_zone_No,flood_prone_zone_Yes
0,1,372,5,5,44.0,4.16,38.4,8,16.6,11.98,...,False,True,True,False,True,False,False,True,False,True
1,2,744,4,5,2.0,5.09,34.2,1,11.3,3.14,...,True,False,True,False,True,False,False,True,True,False
2,2,569,16,22,0.0,1.98,17.1,3,16.2,3.78,...,False,True,True,False,True,False,False,True,True,False
3,2,576,5,9,1.0,3.14,22.7,3,19.0,7.44,...,False,True,True,False,True,False,False,True,True,False
4,1,382,0,22,2.0,2.92,10.7,0,19.5,3.02,...,True,False,True,False,False,True,False,True,True,False

# Separate Features and Targets:

In [43]:
X = df_encoded.drop(columns=["price_lakhs"])
y = df_encoded["price_lakhs"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (5000, 68)
Target shape: (5000,)

# Train Test Split:

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (4000, 68)
Testing data: (1000, 68)

# Training all models together:

In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor
)

models = {
    "Linear Regression": LinearRegression(),

    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        random_state=42
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        n_estimators=200,
        random_state=42
    )
}

trained_models = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    trained_models[name] = model

    print(f"{name} training completed.")

print("\nAll three models trained successfully!")

Linear Regression training completed.
Random Forest training completed.
Gradient Boosting training completed.

All three models trained successfully!

# Evaluate all models together:

In [46]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

metrics_list = []

for name, model in trained_models.items():
    preds = model.predict(X_test)

    metrics_list.append({
        "Model": name,
        "MAE": mean_absolute_error(y_test, preds),
        "RMSE": np.sqrt(mean_squared_error(y_test, preds)),
        "R2 Score": r2_score(y_test, preds)
    })

print("Evaluation of all three models completed.")

Evaluation of all three models completed.

# Metrics Table Comparison:

In [47]:
metrics_df = pd.DataFrame(metrics_list)

metrics_df = metrics_df.sort_values(
    "R2 Score",
    ascending=False
).reset_index(drop=True)

display(metrics_df.round(4))

               Model      MAE     RMSE  R2 Score
0  Gradient Boosting  27.7185  42.5853    0.9436
1      Random Forest  30.5293  49.9779    0.9223
2  Linear Regression  47.6323  77.8829    0.8114

# Save the best model using joblib:

In [48]:
best_model_name = metrics_df.iloc[0]["Model"]
best_model = trained_models[best_model_name]

joblib.dump(
    best_model,
    "models/best_mumbai_price_model.joblib"
)

joblib.dump(
    list(X_train.columns),
    "models/model_columns.joblib"
)

print("Best model:", best_model_name)
print("Model saved successfully!")
print("Training columns saved successfully!")

Best model: Gradient Boosting
Model saved successfully!
Training columns saved successfully!

# Predict the price of a new property:

In [49]:
new_house = pd.DataFrame([{
    "locality": "Powai",
    "zone": "Western Suburbs",
    "bhk": 2,
    "property_type": "Apartment",
    "carpet_area_sqft": 850,
    "floor_number": 6,
    "total_floors": 20,
    "age_of_building_years": 3,
    "furnishing_status": "Semi-furnished",
    "distance_to_station_km": 2.0,
    "distance_to_business_hub_km": 16,
    "is_gated_society": "Yes",
    "amenities_count": 6,
    "parking_available": "Yes",
    "sea_facing_view": "No",
    "possession_status": "Ready to Move",
    "rera_registered": "Yes",
    "flood_prone_zone": "No",
    "water_supply_hours_per_day": 18,
    "society_maintenance_per_sqft": 5.0
}])

# One-hot encode the new property
new_house_encoded = pd.get_dummies(new_house)

# Load saved model and training columns
loaded_model = joblib.load("models/best_mumbai_price_model.joblib")
loaded_columns = joblib.load("models/model_columns.joblib")

# Align columns with the training data
new_house_encoded = new_house_encoded.reindex(
    columns=loaded_columns,
    fill_value=0
)

# Predict price
predicted_price = loaded_model.predict(new_house_encoded)

print(
    f"Selected model: {best_model_name}"
)

print(
    f"Predicted price: ₹{predicted_price[0]:.2f} lakhs"
)

Selected model: Gradient Boosting
Predicted price: ₹233.76 lakhs

# Conclusion:

The Linear Regression, Random Forest Regressor and Gradient Boosting Regressor models were trained and compared for Mumbai house price prediction. Their performance was evaluated using MAE, RMSE and \(R^2\) Score. The Gradient Boosting achieved the lowest MAE and RMSE and the highest \(R^2\) Score of 0.9436. The best-performing model and its training column list were saved using joblib and used to predict the price of a hypothetical property.